# Generated by Django 3.2.3 on 2021-09-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=200)),
                ('customer_last_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.PositiveBigIntegerField(max_length=9)),
                ('customer_idcard', models.PositiveBigIntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(max_length=200)),
                ('match_tickets', models.IntegerField()),
                ('match_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Staduim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staduim_name', models.CharField(max_length=200)),
                ('staduim_town', models.CharField(max_length=200)),
                ('Staduim_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_category', models.CharField(max_length=200)),
                ('ticket_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_sales.match')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=200)),
                ('sales_customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticket_sales.customer')),
                ('sales_ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticket_sales.tickets')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_staduim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_sales.staduim'),
        ),
    ]
