# Generated by Django 3.2.3 on 2021-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_idcard',
            field=models.PositiveIntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.PositiveIntegerField(max_length=9),
        ),
    ]
