# Generated by Django 3.2.3 on 2021-09-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0002_auto_20210908_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
