# Generated by Django 3.2.3 on 2021-09-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0003_tickets_ticket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_date',
            field=models.DateField(null=True),
        ),
    ]
