# Generated by Django 3.2.3 on 2021-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0004_sales_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='match',
            name='match_round',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
