# Generated by Django 3.2.3 on 2021-09-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0005_auto_20210909_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_shortname', models.CharField(max_length=3, null=True)),
                ('team_flag', models.ImageField(upload_to='media/teams')),
            ],
            options={
                'ordering': ['team_name', 'team_shortname'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket_sales.team', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='ticket_sales.team', verbose_name='Home Team'),
        ),
    ]
